using Domain.Entities.Identity;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infrastructure.SeedData
{
    public static class GovernorateCitySeeder
    {
        public static async Task SeedGovernoratesAndCitiesAsync(IServiceProvider serviceProvider)
        {
            using var scope = serviceProvider.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
            await context.Database.MigrateAsync();

            if (!context.Governorates.Any())
            {
                var governorates = new List<Governorate>
                {
                    new Governorate { GovernorateNameAr = "القاهرة", GovernorateNameEn = "Cairo" },
                    new Governorate { GovernorateNameAr = "الجيزة", GovernorateNameEn = "Giza" },
                    new Governorate { GovernorateNameAr = "الأسكندرية", GovernorateNameEn = "Alexandria" },
                    new Governorate { GovernorateNameAr = "الدقهلية", GovernorateNameEn = "Dakahlia" },
                    new Governorate { GovernorateNameAr = "البحر الأحمر", GovernorateNameEn = "Red Sea" },
                    new Governorate {  GovernorateNameAr = "البحيرة", GovernorateNameEn = "Beheira" },
                    new Governorate {  GovernorateNameAr = "الفيوم", GovernorateNameEn = "Fayoum" },
                    new Governorate {  GovernorateNameAr = "الغربية", GovernorateNameEn = "Gharbiya" },
                    new Governorate { GovernorateNameAr = "الإسماعلية", GovernorateNameEn = "Ismailia" },
                    new Governorate {   GovernorateNameAr = "المنوفية", GovernorateNameEn = "Menofia" },
                    new Governorate {   GovernorateNameAr = "المنيا", GovernorateNameEn = "Minya" },
                    new Governorate {   GovernorateNameAr = "القليوبية", GovernorateNameEn = "Qaliubiya" },
                    new Governorate {   GovernorateNameAr = "الوادي الجديد", GovernorateNameEn = "New Valley" },
                    new Governorate {   GovernorateNameAr = "السويس", GovernorateNameEn = "Suez" },
                    new Governorate {   GovernorateNameAr = "اسوان", GovernorateNameEn = "Aswan" },
                    new Governorate {   GovernorateNameAr = "اسيوط", GovernorateNameEn = "Assiut" },
                    new Governorate {   GovernorateNameAr = "بني سويف", GovernorateNameEn = "Beni Suef" },
                    new Governorate {   GovernorateNameAr = "بورسعيد", GovernorateNameEn = "Port Said" },
                    new Governorate {   GovernorateNameAr = "دمياط", GovernorateNameEn = "Damietta" },
                    new Governorate {   GovernorateNameAr = "الشرقية", GovernorateNameEn = "Sharkia" },
                    new Governorate {   GovernorateNameAr = "جنوب سيناء", GovernorateNameEn = "South Sinai" },
                    new Governorate {   GovernorateNameAr = "كفر الشيخ", GovernorateNameEn = "Kafr Al sheikh" },
                    new Governorate {   GovernorateNameAr = "مطروح", GovernorateNameEn = "Matrouh" },
                    new Governorate {   GovernorateNameAr = "الأقصر", GovernorateNameEn = "Luxor" },
                    new Governorate {   GovernorateNameAr = "قنا", GovernorateNameEn = "Qena" },
                    new Governorate {   GovernorateNameAr = "شمال سيناء", GovernorateNameEn = "North Sinai" },
                    new Governorate {   GovernorateNameAr = "سوهاج", GovernorateNameEn = "Sohag" }
                };

                await context.Governorates.AddRangeAsync(governorates);
                await context.SaveChangesAsync();   
            }                                                               

            if (!context.Districts.Any())
            {
                var cities = new List<City>
                {
                    new City {  GovernorateId = 1, CityNameAr = "15 مايو", CityNameEn = "15 May" },
                    new City {  GovernorateId = 1, CityNameAr = "الازبكية", CityNameEn = "Al Azbakeyah" },
                    new City {  GovernorateId = 1, CityNameAr = "البساتين", CityNameEn = "Al Basatin" },
                    new City { GovernorateId = 1, CityNameAr = "التبين", CityNameEn = "Tebin" },
                    new City { GovernorateId = 1, CityNameAr = "الخليفة", CityNameEn = "El-Khalifa" },
                    new City { GovernorateId = 1, CityNameAr = "الدراسة", CityNameEn = "El darrasa" },
                    new City { GovernorateId = 1, CityNameAr = "الدرب الاحمر", CityNameEn = "Aldarb Alahmar" },
                    new City { GovernorateId = 1, CityNameAr = "الزاوية الحمراء", CityNameEn = "Zawya al-Hamra" },
                    new City { GovernorateId = 1, CityNameAr = "الزيتون", CityNameEn = "El-Zaytoun" },
                    new City { GovernorateId = 1, CityNameAr = "الساحل", CityNameEn = "Sahel" },
                    new City { GovernorateId = 1, CityNameAr = "السلام", CityNameEn = "El Salam" },
                    new City { GovernorateId = 1, CityNameAr = "السيدة زينب", CityNameEn = "Sayeda Zeinab" },
                    new City { GovernorateId = 1, CityNameAr = "الشرابية", CityNameEn = "El Sharabeya" },
                    new City { GovernorateId = 1, CityNameAr = "مدينة الشروق", CityNameEn = "Shorouk" },
                    new City { GovernorateId = 1, CityNameAr = "الظاهر", CityNameEn = "El Daher" },
                    new City { GovernorateId = 1, CityNameAr = "العتبة", CityNameEn = "Ataba" },
                    new City { GovernorateId = 1, CityNameAr = "القاهرة الجديدة", CityNameEn = "New Cairo" },
                    new City { GovernorateId = 1, CityNameAr = "المرج", CityNameEn = "El Marg" },
                    new City { GovernorateId = 1, CityNameAr = "عزبة النخل", CityNameEn = "Ezbet el Nakhl" },
                    new City { GovernorateId = 1, CityNameAr = "المطرية", CityNameEn = "Matareya" },
                    new City { GovernorateId = 1, CityNameAr = "المعادى", CityNameEn = "Maadi" },
                    new City { GovernorateId = 1, CityNameAr = "المعصرة", CityNameEn = "Maasara" },
                    new City { GovernorateId = 1, CityNameAr = "المقطم", CityNameEn = "Mokattam" },
                    new City { GovernorateId = 1, CityNameAr = "المنيل", CityNameEn = "Manyal" },
                    new City { GovernorateId = 1, CityNameAr = "الموسكى", CityNameEn = "Mosky" },
                    new City { GovernorateId = 1, CityNameAr = "النزهة", CityNameEn = "Nozha" },
                    new City { GovernorateId = 1, CityNameAr = "الوايلى", CityNameEn = "Waily" },
                    new City { GovernorateId = 1, CityNameAr = "باب الشعرية", CityNameEn = "Bab al-Shereia" },
                    new City { GovernorateId = 1, CityNameAr = "بولاق", CityNameEn = "Bolaq" },
                    new City { GovernorateId = 1, CityNameAr = "جاردن سيتى", CityNameEn = "Garden City" },
                    new City { GovernorateId = 1, CityNameAr = "حدائق القبة", CityNameEn = "Hadayek El-Kobba" },
                    new City { GovernorateId = 1, CityNameAr = "حلوان", CityNameEn = "Helwan" },
                    new City { GovernorateId = 1, CityNameAr = "دار السلام", CityNameEn = "Dar Al Salam" },
                    new City { GovernorateId = 1, CityNameAr = "شبرا", CityNameEn = "Shubra" },
                    new City { GovernorateId = 1, CityNameAr = "طره", CityNameEn = "Tura" },
                    new City { GovernorateId = 1, CityNameAr = "عابدين", CityNameEn = "Abdeen" },
                    new City { GovernorateId = 1, CityNameAr = "عباسية", CityNameEn = "Abaseya" },
                    new City { GovernorateId = 1, CityNameAr = "عين شمس", CityNameEn = "Ain Shams" },
                    new City { GovernorateId = 1, CityNameAr = "مدينة نصر", CityNameEn = "Nasr City" },
                    new City { GovernorateId = 1, CityNameAr = "مصر الجديدة", CityNameEn = "New Heliopolis" },
                    new City { GovernorateId = 1, CityNameAr = "مصر القديمة", CityNameEn = "Masr Al Qadima" },
                    new City { GovernorateId = 1, CityNameAr = "منشية ناصر", CityNameEn = "Mansheya Nasir" },
                    new City { GovernorateId = 1, CityNameAr = "مدينة بدر", CityNameEn = "Badr City" },
                    new City {   GovernorateId = 1, CityNameAr = "مدينة العبور", CityNameEn = "Obour City" },
                    new City {   GovernorateId = 1, CityNameAr = "وسط البلد", CityNameEn = "Cairo Downtown" },
                    new City {   GovernorateId = 1, CityNameAr = "الزمالك", CityNameEn = "Zamalek" },
                    new City {   GovernorateId = 1, CityNameAr = "قصر النيل", CityNameEn = "Kasr El Nile" },
                    new City {   GovernorateId = 1, CityNameAr = "الرحاب", CityNameEn = "Rehab" },
                    new City {   GovernorateId = 1, CityNameAr = "القطامية", CityNameEn = "Katameya" },
                    new City {   GovernorateId = 1, CityNameAr = "مدينتي", CityNameEn = "Madinty" },
                    new City {   GovernorateId = 1, CityNameAr = "روض الفرج", CityNameEn = "Rod Alfarag" },
                    new City {   GovernorateId = 1, CityNameAr = "شيراتون", CityNameEn = "Sheraton" },
                    new City {   GovernorateId = 1, CityNameAr = "الجمالية", CityNameEn = "El-Gamaleya" },
                    new City {   GovernorateId = 1, CityNameAr = "العاشر من رمضان", CityNameEn = "10th of Ramadan City" },
                    new City {   GovernorateId = 1, CityNameAr = "الحلمية", CityNameEn = "Helmeyat Alzaytoun" },
                    new City {   GovernorateId = 1, CityNameAr = "النزهة الجديدة", CityNameEn = "New Nozha" },
                    new City {   GovernorateId = 1, CityNameAr = "العاصمة الإدارية", CityNameEn = "Capital New" },
                    new City {   GovernorateId = 2, CityNameAr = "الجيزة", CityNameEn = "Giza" },
                    new City {   GovernorateId = 2, CityNameAr = "السادس من أكتوبر", CityNameEn = "Sixth of October" },
                    new City {   GovernorateId = 2, CityNameAr = "الشيخ زايد", CityNameEn = "Cheikh Zayed" },
                    new City {   GovernorateId = 2, CityNameAr = "الحوامدية", CityNameEn = "Hawamdiyah" },
                    new City {   GovernorateId = 2, CityNameAr = "البدرشين", CityNameEn = "Al Badrasheen" },
                    new City {   GovernorateId = 2, CityNameAr = "الصف", CityNameEn = "Saf" },
                    new City {   GovernorateId = 2, CityNameAr = "أطفيح", CityNameEn = "Atfih" },
                    new City {   GovernorateId = 2, CityNameAr = "العياط", CityNameEn = "Al Ayat" },
                    new City {   GovernorateId = 2, CityNameAr = "الباويطي", CityNameEn = "Al-Bawaiti" },
                    new City {   GovernorateId = 2, CityNameAr = "منشأة القناطر", CityNameEn = "ManshiyetAl Qanater" },
                    new City {   GovernorateId = 2, CityNameAr = "أوسيم", CityNameEn = "Oaseem" },
                    new City {   GovernorateId = 2, CityNameAr = "كرداسة", CityNameEn = "Kerdasa" },
                    new City {   GovernorateId = 2, CityNameAr = "أبو النمرس", CityNameEn = "Abu Nomros" },
                    new City {   GovernorateId = 2, CityNameAr = "كفر غطاطي", CityNameEn = "Kafr Ghati" },
                    new City {   GovernorateId = 2, CityNameAr = "منشأة البكاري", CityNameEn = "Manshiyet Al Bakari" },
                    new City {   GovernorateId = 2, CityNameAr = "الدقى", CityNameEn = "Dokki" },
                    new City {   GovernorateId = 2, CityNameAr = "العجوزة", CityNameEn = "Agouza" },
                    new City {   GovernorateId = 2, CityNameAr = "الهرم", CityNameEn = "Haram" },
                    new City {   GovernorateId = 2, CityNameAr = "الوراق", CityNameEn = "Warraq" },
                    new City {   GovernorateId = 2, CityNameAr = "امبابة", CityNameEn = "Imbaba" },
                    new City {   GovernorateId = 2, CityNameAr = "بولاق الدكرور", CityNameEn = "Boulaq Dakrour" },
                    new City {   GovernorateId = 2, CityNameAr = "الواحات البحرية", CityNameEn = "Al Wahat Al Baharia" },
                    new City {   GovernorateId = 2, CityNameAr = "العمرانية", CityNameEn = "Omraneya" },
                    new City {   GovernorateId = 2, CityNameAr = "المنيب", CityNameEn = "Moneeb" },
                    new City {   GovernorateId = 2, CityNameAr = "بين السرايات", CityNameEn = "Bin Alsarayat" },
                    new City {   GovernorateId = 2, CityNameAr = "الكيت كات", CityNameEn = "Kit Kat" },
                    new City {   GovernorateId = 2, CityNameAr = "المهندسين", CityNameEn = "Mohandessin" },
                    new City {   GovernorateId = 2, CityNameAr = "فيصل", CityNameEn = "Faisal" },
                    new City {   GovernorateId = 2, CityNameAr = "أبو رواش", CityNameEn = "Abu Rawash" },
                    new City {   GovernorateId = 2, CityNameAr = "حدائق الأهرام", CityNameEn = "Hadayek Alahram" },
                    new City {   GovernorateId = 2, CityNameAr = "الحرانية", CityNameEn = "Haraneya" },
                    new City {   GovernorateId = 2, CityNameAr = "حدائق اكتوبر", CityNameEn = "Hadayek October" },
                    new City {   GovernorateId = 2, CityNameAr = "صفط اللبن", CityNameEn = "Saft Allaban" },
                    new City {   GovernorateId = 2, CityNameAr = "القرية الذكية", CityNameEn = "Smart Village" },
                    new City {   GovernorateId = 2, CityNameAr = "ارض اللواء", CityNameEn = "Ard Ellwaa" },
                    new City {   GovernorateId = 3, CityNameAr = "ابو قير", CityNameEn = "Abu Qir" },
                    new City {   GovernorateId = 3, CityNameAr = "الابراهيمية", CityNameEn = "Al Ibrahimeyah" },
                    new City {   GovernorateId = 3, CityNameAr = "الأزاريطة", CityNameEn = "Azarita" },
                    new City {   GovernorateId = 3, CityNameAr = "الانفوشى", CityNameEn = "Anfoushi" },
                    new City {   GovernorateId = 3, CityNameAr = "الدخيلة", CityNameEn = "Dekheila" },
                    new City {   GovernorateId = 3, CityNameAr = "السيوف", CityNameEn = "El Soyof" },
                    new City {   GovernorateId = 3, CityNameAr = "العامرية", CityNameEn = "Ameria" },
                    new City {   GovernorateId = 3, CityNameAr = "اللبان", CityNameEn = "El Labban" },
                    new City {   GovernorateId = 3, CityNameAr = "المفروزة", CityNameEn = "Al Mafrouza" },
                    new City {   GovernorateId = 3, CityNameAr = "المنتزه", CityNameEn = "El Montaza" },
                    new City {   GovernorateId = 3, CityNameAr = "المنشية", CityNameEn = "Mansheya" },
                    new City {   GovernorateId = 3, CityNameAr = "الناصرية", CityNameEn = "Naseria" },
                    new City {   GovernorateId = 3, CityNameAr = "امبروزو", CityNameEn = "Ambrozo" },
                    new City {   GovernorateId = 3, CityNameAr = "باب شرق", CityNameEn = "Bab Sharq" },
                    new City {   GovernorateId = 3, CityNameAr = "برج العرب", CityNameEn = "Bourj Alarab" },
                    new City {   GovernorateId = 3, CityNameAr = "ستانلى", CityNameEn = "Stanley" },
                    new City {   GovernorateId = 3, CityNameAr = "سموحة", CityNameEn = "Smouha" },
                    new City {   GovernorateId = 3, CityNameAr = "سيدى بشر", CityNameEn = "Sidi Bishr" },
                    new City {   GovernorateId = 3, CityNameAr = "شدس", CityNameEn = "Shads" },
                    new City {   GovernorateId = 3, CityNameAr = "غيط العنب", CityNameEn = "Gheet Alenab" },
                    new City {   GovernorateId = 3, CityNameAr = "فلمينج", CityNameEn = "Fleming" },
                    new City {   GovernorateId = 3, CityNameAr = "فيكتوريا", CityNameEn = "Victoria" },
                    new City {   GovernorateId = 3, CityNameAr = "كامب شيزار", CityNameEn = "Camp Shizar" },
                    new City {   GovernorateId = 3, CityNameAr = "كرموز", CityNameEn = "Karmooz" },
                    new City {   GovernorateId = 3, CityNameAr = "محطة الرمل", CityNameEn = "Mahta Alraml" },
                    new City {   GovernorateId = 3, CityNameAr = "مينا البصل", CityNameEn = "Mina El-Basal" },
                    new City {   GovernorateId = 3, CityNameAr = "العصافرة", CityNameEn = "Asafra" },
                    new City {   GovernorateId = 3, CityNameAr = "العجمي", CityNameEn = "Agamy" },
                    new City {   GovernorateId = 3, CityNameAr = "بكوس", CityNameEn = "Bakos" },
                    new City {   GovernorateId = 3, CityNameAr = "بولكلي", CityNameEn = "Boulkly" },
                    new City {   GovernorateId = 3, CityNameAr = "كليوباترا", CityNameEn = "Cleopatra" },
                    new City {   GovernorateId = 3, CityNameAr = "جليم", CityNameEn = "Glim" },
                    new City {   GovernorateId = 3, CityNameAr = "المعمورة", CityNameEn = "Al Mamurah" },
                    new City {   GovernorateId = 3, CityNameAr = "المندرة", CityNameEn = "Al Mandara" },
                    new City {   GovernorateId = 3, CityNameAr = "محرم بك", CityNameEn = "Moharam Bek" },
                    new City {   GovernorateId = 3, CityNameAr = "الشاطبي", CityNameEn = "Elshatby" },
                    new City {   GovernorateId = 3, CityNameAr = "سيدي جابر", CityNameEn = "Sidi Gaber" },
                    new City {   GovernorateId = 3, CityNameAr = "الساحل الشمالي", CityNameEn = "North Coast/sahel" },
                    new City {   GovernorateId = 3, CityNameAr = "الحضرة", CityNameEn = "Alhadra" },
                    new City {   GovernorateId = 3, CityNameAr = "العطارين", CityNameEn = "Alattarin" },
                    new City {   GovernorateId = 3, CityNameAr = "سيدي كرير", CityNameEn = "Sidi Kerir" },
                    new City {   GovernorateId = 3, CityNameAr = "الجمرك", CityNameEn = "Elgomrok" },
                    new City {   GovernorateId = 3, CityNameAr = "المكس", CityNameEn = "Al Max" },
                    new City {   GovernorateId = 3, CityNameAr = "مارينا", CityNameEn = "Marina" },
                    new City {   GovernorateId = 4, CityNameAr = "المنصورة", CityNameEn = "Mansoura" },
                    new City {   GovernorateId = 4, CityNameAr = "طلخا", CityNameEn = "Talkha" },
                    new City {   GovernorateId = 4, CityNameAr = "ميت غمر", CityNameEn = "Mitt Ghamr" },
                    new City {   GovernorateId = 4, CityNameAr = "دكرنس", CityNameEn = "Dekernes" },
                    new City {   GovernorateId = 4, CityNameAr = "أجا", CityNameEn = "Aga" },
                    new City {   GovernorateId = 4, CityNameAr = "منية النصر", CityNameEn = "Menia El Nasr" },
                    new City {   GovernorateId = 4, CityNameAr = "السنبلاوين", CityNameEn = "Sinbillawin" },
                    new City {   GovernorateId = 4, CityNameAr = "الكردي", CityNameEn = "El Kurdi" },
                    new City {   GovernorateId = 4, CityNameAr = "بني عبيد", CityNameEn = "Bani Ubaid" },
                    new City {   GovernorateId = 4, CityNameAr = "المنزلة", CityNameEn = "Al Manzala" },
                    new City {   GovernorateId = 4, CityNameAr = "تمي الأمديد", CityNameEn = "tami al'amdid" },
                    new City {   GovernorateId = 4, CityNameAr = "الجمالية", CityNameEn = "aljamalia" },
                    new City {   GovernorateId = 4, CityNameAr = "شربين", CityNameEn = "Sherbin" },
                    new City {   GovernorateId = 4, CityNameAr = "المطرية", CityNameEn = "Mataria" },
                    new City {   GovernorateId = 4, CityNameAr = "بلقاس", CityNameEn = "Belqas" },
                    new City {   GovernorateId = 4, CityNameAr = "ميت سلسيل", CityNameEn = "Meet Salsil" },
                    new City {   GovernorateId = 4, CityNameAr = "جمصة", CityNameEn = "Gamasa" },
                    new City {   GovernorateId = 4, CityNameAr = "محلة دمنة", CityNameEn = "Mahalat Damana" },
                    new City {   GovernorateId = 4, CityNameAr = "نبروه", CityNameEn = "Nabroh" },
                    new City {   GovernorateId = 5, CityNameAr = "الغردقة", CityNameEn = "Hurghada" },
                    new City {   GovernorateId = 5, CityNameAr = "رأس غارب", CityNameEn = "Ras Ghareb" },
                    new City {   GovernorateId = 5, CityNameAr = "سفاجا", CityNameEn = "Safaga" },
                    new City {   GovernorateId = 5, CityNameAr = "القصير", CityNameEn = "El Qusiar" },
                    new City {   GovernorateId = 5, CityNameAr = "مرسى علم", CityNameEn = "Marsa Alam" },
                    new City {   GovernorateId = 5, CityNameAr = "الشلاتين", CityNameEn = "Shalatin" },
                    new City {   GovernorateId = 5, CityNameAr = "حلايب", CityNameEn = "Halaib" },
                    new City {   GovernorateId = 5, CityNameAr = "الدهار", CityNameEn = "Aldahar" },
                    new City {   GovernorateId = 6, CityNameAr = "دمنهور", CityNameEn = "Damanhour" },
                    new City {   GovernorateId = 6, CityNameAr = "كفر الدوار", CityNameEn = "Kafr El Dawar" },
                    new City {   GovernorateId = 6, CityNameAr = "رشيد", CityNameEn = "Rashid" },
                    new City {   GovernorateId = 6, CityNameAr = "إدكو", CityNameEn = "Edco" },
                    new City {   GovernorateId = 6, CityNameAr = "أبو المطامير", CityNameEn = "Abu al-Matamir" },
                    new City {   GovernorateId = 6, CityNameAr = "أبو حمص", CityNameEn = "Abu Homs" },
                    new City {   GovernorateId = 6, CityNameAr = "الدلنجات", CityNameEn = "Delengat" },
                    new City {   GovernorateId = 6, CityNameAr = "المحمودية", CityNameEn = "Mahmoudiyah" },
                    new City {   GovernorateId = 6, CityNameAr = "الرحمانية", CityNameEn = "Rahmaniyah" },
                    new City {   GovernorateId = 6, CityNameAr = "إيتاي البارود", CityNameEn = "Itai Baroud" },
                    new City {   GovernorateId = 6, CityNameAr = "حوش عيسى", CityNameEn = "Housh Eissa" },
                    new City {   GovernorateId = 6, CityNameAr = "شبراخيت", CityNameEn = "Shubrakhit" },
                    new City {   GovernorateId = 6, CityNameAr = "كوم حمادة", CityNameEn = "Kom Hamada" },
                    new City {   GovernorateId = 6, CityNameAr = "بدر", CityNameEn = "Badr" },
                    new City {   GovernorateId = 6, CityNameAr = "وادي النطرون", CityNameEn = "Wadi Natrun" },
                    new City {   GovernorateId = 6, CityNameAr = "النوبارية الجديدة", CityNameEn = "New Nubaria" },
                    new City {   GovernorateId = 6, CityNameAr = "النوبارية", CityNameEn = "Alnoubareya" },
                    new City {   GovernorateId = 7, CityNameAr = "الفيوم", CityNameEn = "Fayoum" },
                    new City {   GovernorateId = 7, CityNameAr = "الفيوم الجديدة", CityNameEn = "Fayoum El Gedida" },
                    new City {   GovernorateId = 7, CityNameAr = "طامية", CityNameEn = "Tamiya" },
                    new City {   GovernorateId = 7, CityNameAr = "سنورس", CityNameEn = "Snores" },
                    new City {   GovernorateId = 7, CityNameAr = "إطسا", CityNameEn = "Etsa" },
                    new City {   GovernorateId = 7, CityNameAr = "إبشواي", CityNameEn = "Epschway" },
                    new City {   GovernorateId = 7, CityNameAr = "يوسف الصديق", CityNameEn = "Yusuf El Sediaq" },
                    new City {   GovernorateId = 7, CityNameAr = "الحادقة", CityNameEn = "Hadqa" },
                    new City {   GovernorateId = 7, CityNameAr = "اطسا", CityNameEn = "Atsa" },
                    new City {   GovernorateId = 7, CityNameAr = "الجامعة", CityNameEn = "Algamaa" },
                    new City {   GovernorateId = 7, CityNameAr = "السيالة", CityNameEn = "Sayala" },
                    new City {   GovernorateId = 8, CityNameAr = "طنطا", CityNameEn = "Tanta" },
                    new City {   GovernorateId = 8, CityNameAr = "المحلة الكبرى", CityNameEn = "Al Mahalla Al Kobra" },
                    new City {   GovernorateId = 8, CityNameAr = "كفر الزيات", CityNameEn = "Kafr El Zayat" },
                    new City {   GovernorateId = 8, CityNameAr = "زفتى", CityNameEn = "Zefta" },
                    new City {   GovernorateId = 8, CityNameAr = "السنطة", CityNameEn = "El Santa" },
                    new City {   GovernorateId = 8, CityNameAr = "قطور", CityNameEn = "Qutour" },
                    new City {   GovernorateId = 8, CityNameAr = "بسيون", CityNameEn = "Basion" },
                    new City {   GovernorateId = 8, CityNameAr = "سمنود", CityNameEn = "Samannoud" },
                    new City {   GovernorateId = 9, CityNameAr = "الإسماعيلية", CityNameEn = "Ismailia" },
                    new City {   GovernorateId = 9, CityNameAr = "فايد", CityNameEn = "Fayed" },
                    new City {   GovernorateId = 9, CityNameAr = "القنطرة شرق", CityNameEn = "Qantara Sharq" },
                    new City {   GovernorateId = 9, CityNameAr = "القنطرة غرب", CityNameEn = "Qantara Gharb" },
                    new City {   GovernorateId = 9, CityNameAr = "التل الكبير", CityNameEn = "El Tal El Kabier" },
                    new City {   GovernorateId = 9, CityNameAr = "أبو صوير", CityNameEn = "Abu Sawir" },
                    new City {   GovernorateId = 9, CityNameAr = "القصاصين الجديدة", CityNameEn = "Kasasien El Gedida" },
                    new City {   GovernorateId = 9, CityNameAr = "نفيشة", CityNameEn = "Nefesha" },
                    new City {   GovernorateId = 9, CityNameAr = "الشيخ زايد", CityNameEn = "Sheikh Zayed" },
                    new City {   GovernorateId = 10, CityNameAr = "شبين الكوم", CityNameEn = "Shbeen El Koom" },
                    new City {   GovernorateId = 10, CityNameAr = "مدينة السادات", CityNameEn = "Sadat City" },
                    new City {   GovernorateId = 10, CityNameAr = "منوف", CityNameEn = "Menouf" },
                    new City {   GovernorateId = 10, CityNameAr = "سرس الليان", CityNameEn = "Sars El-Layan" },
                    new City {   GovernorateId = 10, CityNameAr = "أشمون", CityNameEn = "Ashmon" },
                    new City {   GovernorateId = 10, CityNameAr = "الباجور", CityNameEn = "Al Bagor" },
                    new City {   GovernorateId = 10, CityNameAr = "قويسنا", CityNameEn = "Quesna" },
                    new City {   GovernorateId = 10, CityNameAr = "بركة السبع", CityNameEn = "Berkat El Saba" },
                    new City {   GovernorateId = 10, CityNameAr = "تلا", CityNameEn = "Tala" },
                    new City {   GovernorateId = 10, CityNameAr = "الشهداء", CityNameEn = "Al Shohada" },
                    new City {   GovernorateId = 11, CityNameAr = "المنيا", CityNameEn = "Minya" },
                    new City {   GovernorateId = 11, CityNameAr = "المنيا الجديدة", CityNameEn = "Minya El Gedida" },
                    new City {   GovernorateId = 11, CityNameAr = "العدوة", CityNameEn = "El Adwa" },
                    new City {   GovernorateId = 11, CityNameAr = "مغاغة", CityNameEn = "Magagha" },
                    new City {   GovernorateId = 11, CityNameAr = "بني مزار", CityNameEn = "Bani Mazar" },
                    new City {   GovernorateId = 11, CityNameAr = "مطاي", CityNameEn = "Mattay" },
                    new City {   GovernorateId = 11, CityNameAr = "سمالوط", CityNameEn = "Samalut" },
                    new City {   GovernorateId = 11, CityNameAr = "المدينة الفكرية", CityNameEn = "Madinat El Fekria" },
                    new City {   GovernorateId = 11, CityNameAr = "ملوي", CityNameEn = "Meloy" },
                    new City {   GovernorateId = 11, CityNameAr = "دير مواس", CityNameEn = "Deir Mawas" },
                    new City {   GovernorateId = 11, CityNameAr = "ابو قرقاص", CityNameEn = "Abu Qurqas" },
                    new City {   GovernorateId = 11, CityNameAr = "ارض سلطان", CityNameEn = "Ard Sultan" },
                    new City {   GovernorateId = 12, CityNameAr = "بنها", CityNameEn = "Banha" },
                    new City {   GovernorateId = 12, CityNameAr = "قليوب", CityNameEn = "Qalyub" },
                    new City {   GovernorateId = 12, CityNameAr = "شبرا الخيمة", CityNameEn = "Shubra Al Khaimah" },
                    new City {   GovernorateId = 12, CityNameAr = "القناطر الخيرية", CityNameEn = "Al Qanater Charity" },
                    new City {   GovernorateId = 12, CityNameAr = "الخانكة", CityNameEn = "Khanka" },
                    new City {   GovernorateId = 12, CityNameAr = "كفر شكر", CityNameEn = "Kafr Shukr" },
                    new City {   GovernorateId = 12, CityNameAr = "طوخ", CityNameEn = "Tukh" },
                    new City {   GovernorateId = 12, CityNameAr = "قها", CityNameEn = "Qaha" },
                    new City {   GovernorateId = 12, CityNameAr = "العبور", CityNameEn = "Obour" },
                    new City {   GovernorateId = 12, CityNameAr = "الخصوص", CityNameEn = "Khosous" },
                    new City {   GovernorateId = 12, CityNameAr = "شبين القناطر", CityNameEn = "Shibin Al Qanater" },
                    new City {   GovernorateId = 12, CityNameAr = "مسطرد", CityNameEn = "Mostorod" },
                    new City {   GovernorateId = 13, CityNameAr = "الخارجة", CityNameEn = "El Kharga" },
                    new City {   GovernorateId = 13, CityNameAr = "باريس", CityNameEn = "Paris" },
                    new City {   GovernorateId = 13, CityNameAr = "موط", CityNameEn = "Mout" },
                    new City {   GovernorateId = 13, CityNameAr = "الفرافرة", CityNameEn = "Farafra" },
                    new City {   GovernorateId = 13, CityNameAr = "بلاط", CityNameEn = "Balat" },
                    new City {   GovernorateId = 13, CityNameAr = "الداخلة", CityNameEn = "Dakhla" },
                    new City {   GovernorateId = 14, CityNameAr = "السويس", CityNameEn = "Suez" },
                    new City {   GovernorateId = 14, CityNameAr = "الجناين", CityNameEn = "Alganayen" },
                    new City {   GovernorateId = 14, CityNameAr = "عتاقة", CityNameEn = "Ataqah" },
                    new City {   GovernorateId = 14, CityNameAr = "العين السخنة", CityNameEn = "Ain Sokhna" },
                    new City {   GovernorateId = 14, CityNameAr = "فيصل", CityNameEn = "Faysal" },
                    new City {   GovernorateId = 15, CityNameAr = "أسوان", CityNameEn = "Aswan" },
                    new City {   GovernorateId = 15, CityNameAr = "أسوان الجديدة", CityNameEn = "Aswan El Gedida" },
                    new City {   GovernorateId = 15, CityNameAr = "دراو", CityNameEn = "Drau" },
                    new City {   GovernorateId = 15, CityNameAr = "كوم أمبو", CityNameEn = "Kom Ombo" },
                    new City {   GovernorateId = 15, CityNameAr = "نصر النوبة", CityNameEn = "Nasr Al Nuba" },
                    new City {   GovernorateId = 15, CityNameAr = "كلابشة", CityNameEn = "Kalabsha" },
                    new City {   GovernorateId = 15, CityNameAr = "إدفو", CityNameEn = "Edfu" },
                    new City {   GovernorateId = 15, CityNameAr = "الرديسية", CityNameEn = "Al-Radisiyah" },
                    new City {   GovernorateId = 15, CityNameAr = "البصيلية", CityNameEn = "Al Basilia" },
                    new City {   GovernorateId = 15, CityNameAr = "السباعية", CityNameEn = "Al Sibaeia" },
                    new City {   GovernorateId = 15, CityNameAr = "ابوسمبل السياحية", CityNameEn = "Abo Simbl Al Siyahia" },
                    new City {   GovernorateId = 15, CityNameAr = "مرسى علم", CityNameEn = "Marsa Alam" },
                    new City {   GovernorateId = 16, CityNameAr = "أسيوط", CityNameEn = "Assiut" },
                    new City {   GovernorateId = 16, CityNameAr = "أسيوط الجديدة", CityNameEn = "Assiut El Gedida" },
                    new City {   GovernorateId = 16, CityNameAr = "ديروط", CityNameEn = "Dayrout" },
                    new City {   GovernorateId = 16, CityNameAr = "منفلوط", CityNameEn = "Manfalut" },
                    new City {   GovernorateId = 16, CityNameAr = "القوصية", CityNameEn = "Qusiya" },
                    new City {   GovernorateId = 16, CityNameAr = "أبنوب", CityNameEn = "Abnoub" },
                    new City {   GovernorateId = 16, CityNameAr = "أبو تيج", CityNameEn = "Abu Tig" },
                    new City {   GovernorateId = 16, CityNameAr = "الغنايم", CityNameEn = "El Ghanaim" },
                    new City {   GovernorateId = 16, CityNameAr = "ساحل سليم", CityNameEn = "Sahel Selim" },
                    new City {   GovernorateId = 16, CityNameAr = "البداري", CityNameEn = "El Badari" },
                    new City {   GovernorateId = 16, CityNameAr = "صدفا", CityNameEn = "Sidfa" },
                    new City {   GovernorateId = 17, CityNameAr = "بني سويف", CityNameEn = "Bani Sweif" },
                    new City {   GovernorateId = 17, CityNameAr = "بني سويف الجديدة", CityNameEn = "Beni Suef El Gedida" },
                    new City {   GovernorateId = 17, CityNameAr = "الواسطى", CityNameEn = "Al Wasta" },
                    new City {   GovernorateId = 17, CityNameAr = "ناصر", CityNameEn = "Naser" },
                    new City {   GovernorateId = 17, CityNameAr = "إهناسيا", CityNameEn = "Ehnasia" },
                    new City {   GovernorateId = 17, CityNameAr = "ببا", CityNameEn = "beba" },
                    new City {   GovernorateId = 17, CityNameAr = "الفشن", CityNameEn = "Fashn" },
                    new City {   GovernorateId = 17, CityNameAr = "سمسطا", CityNameEn = "Somasta" },
                    new City {   GovernorateId = 17, CityNameAr = "الاباصيرى", CityNameEn = "Alabbaseri" },
                    new City {   GovernorateId = 17, CityNameAr = "مقبل", CityNameEn = "Mokbel" },
                    new City {   GovernorateId = 18, CityNameAr = "بورسعيد", CityNameEn = "PorSaid" },
                    new City {   GovernorateId = 18, CityNameAr = "بورفؤاد", CityNameEn = "Port Fouad" },
                    new City {   GovernorateId = 18, CityNameAr = "العرب", CityNameEn = "Alarab" },
                    new City {   GovernorateId = 18, CityNameAr = "حى الزهور", CityNameEn = "Zohour" },
                    new City {   GovernorateId = 18, CityNameAr = "حى الشرق", CityNameEn = "Alsharq" },
                    new City {   GovernorateId = 18, CityNameAr = "حى الضواحى", CityNameEn = "Aldawahi" },
                    new City {   GovernorateId = 18, CityNameAr = "حى المناخ", CityNameEn = "Almanakh" },
                    new City {   GovernorateId = 18, CityNameAr = "حى مبارك", CityNameEn = "Mubarak" },
                    new City {   GovernorateId = 19, CityNameAr = "دمياط", CityNameEn = "Damietta" },
                    new City {   GovernorateId = 19, CityNameAr = "دمياط الجديدة", CityNameEn = "New Damietta" },
                    new City {   GovernorateId = 19, CityNameAr = "رأس البر", CityNameEn = "Ras El Bar" },
                    new City {   GovernorateId = 19, CityNameAr = "فارسكور", CityNameEn = "Faraskour" },
                    new City {   GovernorateId = 19, CityNameAr = "الزرقا", CityNameEn = "Zarqa" },
                    new City {   GovernorateId = 19, CityNameAr = "السرو", CityNameEn = "alsaru" },
                    new City {   GovernorateId = 19, CityNameAr = "الروضة", CityNameEn = "alruwda" },
                    new City {   GovernorateId = 19, CityNameAr = "كفر البطيخ", CityNameEn = "Kafr El-Batikh" },
                    new City {   GovernorateId = 19, CityNameAr = "عزبة البرج", CityNameEn = "Azbet Al Burg" },
                    new City {   GovernorateId = 19, CityNameAr = "ميت أبو غالب", CityNameEn = "Meet Abou Ghalib" },
                    new City {   GovernorateId = 19, CityNameAr = "كفر سعد", CityNameEn = "Kafr Saad" },
                    new City {   GovernorateId = 20, CityNameAr = "الزقازيق", CityNameEn = "Zagazig" },
                    new City {   GovernorateId = 20, CityNameAr = "العاشر من رمضان", CityNameEn = "Al Ashr Men Ramadan" },
                    new City {   GovernorateId = 20, CityNameAr = "منيا القمح", CityNameEn = "Minya Al Qamh" },
                    new City {   GovernorateId = 20, CityNameAr = "بلبيس", CityNameEn = "Belbeis" },
                    new City {   GovernorateId = 20, CityNameAr = "مشتول السوق", CityNameEn = "Mashtoul El Souq" },
                    new City {   GovernorateId = 20, CityNameAr = "القنايات", CityNameEn = "Qenaiat" },
                    new City {   GovernorateId = 20, CityNameAr = "أبو حماد", CityNameEn = "Abu Hammad" },
                    new City {   GovernorateId = 20, CityNameAr = "القرين", CityNameEn = "El Qurain" },
                    new City {   GovernorateId = 20, CityNameAr = "ههيا", CityNameEn = "Hehia" },
                    new City {   GovernorateId = 20, CityNameAr = "أبو كبير", CityNameEn = "Abu Kabir" },
                    new City {   GovernorateId = 20, CityNameAr = "فاقوس", CityNameEn = "Faccus" },
                    new City {   GovernorateId = 20, CityNameAr = "الصالحية الجديدة", CityNameEn = "El Salihia El Gedida" },
                    new City {   GovernorateId = 20, CityNameAr = "الإبراهيمية", CityNameEn = "Al Ibrahimiyah" },
                    new City {   GovernorateId = 20, CityNameAr = "ديرب نجم", CityNameEn = "Deirb Negm" },
                    new City {   GovernorateId = 20, CityNameAr = "كفر صقر", CityNameEn = "Kafr Saqr" },
                    new City {   GovernorateId = 20, CityNameAr = "أولاد صقر", CityNameEn = "Awlad Saqr" },
                    new City {   GovernorateId = 20, CityNameAr = "الحسينية", CityNameEn = "Husseiniya" },
                    new City {   GovernorateId = 20, CityNameAr = "صان الحجر القبلية", CityNameEn = "san alhajar alqablia" },
                    new City {   GovernorateId = 20, CityNameAr = "منشأة أبو عمر", CityNameEn = "Manshayat Abu Omar" },
                    new City {   GovernorateId = 21, CityNameAr = "الطور", CityNameEn = "Al Toor" },
                    new City {   GovernorateId = 21, CityNameAr = "شرم الشيخ", CityNameEn = "Sharm El-Shaikh" },
                    new City {   GovernorateId = 21, CityNameAr = "دهب", CityNameEn = "Dahab" },
                    new City {   GovernorateId = 21, CityNameAr = "نويبع", CityNameEn = "Nuweiba" },
                    new City {   GovernorateId = 21, CityNameAr = "طابا", CityNameEn = "Taba" },
                    new City {   GovernorateId = 21, CityNameAr = "سانت كاترين", CityNameEn = "Saint Catherine" },
                    new City {   GovernorateId = 21, CityNameAr = "أبو رديس", CityNameEn = "Abu Redis" },
                    new City {   GovernorateId = 21, CityNameAr = "أبو زنيمة", CityNameEn = "Abu Zenaima" },
                    new City {   GovernorateId = 21, CityNameAr = "رأس سدر", CityNameEn = "Ras Sidr" },
                    new City {   GovernorateId = 22, CityNameAr = "كفر الشيخ", CityNameEn = "Kafr El Sheikh" },
                    new City {   GovernorateId = 22, CityNameAr = "وسط البلد كفر الشيخ", CityNameEn = "Kafr El Sheikh Downtown" },
                    new City {   GovernorateId = 22, CityNameAr = "دسوق", CityNameEn = "Desouq" },
                    new City {   GovernorateId = 22, CityNameAr = "فوه", CityNameEn = "Fooh" },
                    new City {   GovernorateId = 22, CityNameAr = "مطوبس", CityNameEn = "Metobas" },
                    new City {   GovernorateId = 22, CityNameAr = "برج البرلس", CityNameEn = "Burg Al Burullus" },
                    new City {   GovernorateId = 22, CityNameAr = "بلطيم", CityNameEn = "Baltim" },
                    new City {   GovernorateId = 22, CityNameAr = "مصيف بلطيم", CityNameEn = "Masief Baltim" },
                    new City {   GovernorateId = 22, CityNameAr = "الحامول", CityNameEn = "Hamol" },
                    new City {   GovernorateId = 22, CityNameAr = "بيلا", CityNameEn = "Bella" },
                    new City {   GovernorateId = 22, CityNameAr = "الرياض", CityNameEn = "Riyadh" },
                    new City {   GovernorateId = 22, CityNameAr = "سيدي سالم", CityNameEn = "Sidi Salm" },
                    new City {   GovernorateId = 22, CityNameAr = "قلين", CityNameEn = "Qellen" },
                    new City {   GovernorateId = 22, CityNameAr = "سيدي غازي", CityNameEn = "Sidi Ghazi" },
                    new City {   GovernorateId = 23, CityNameAr = "مرسى مطروح", CityNameEn = "Marsa Matrouh" },
                    new City {   GovernorateId = 23, CityNameAr = "الحمام", CityNameEn = "El Hamam" },
                    new City {   GovernorateId = 23, CityNameAr = "العلمين", CityNameEn = "Alamein" },
                    new City {   GovernorateId = 23, CityNameAr = "الضبعة", CityNameEn = "Dabaa" },
                    new City {   GovernorateId = 23, CityNameAr = "النجيلة", CityNameEn = "Al-Nagila" },
                    new City {   GovernorateId = 23, CityNameAr = "سيدي براني", CityNameEn = "Sidi Brani" },
                    new City {   GovernorateId = 23, CityNameAr = "السلوم", CityNameEn = "Salloum" },
                    new City {   GovernorateId = 23, CityNameAr = "سيوة", CityNameEn = "Siwa" },
                    new City {   GovernorateId = 23, CityNameAr = "مارينا", CityNameEn = "Marina" },
                    new City {   GovernorateId = 23, CityNameAr = "الساحل الشمالى", CityNameEn = "North Coast" },
                    new City {   GovernorateId = 24, CityNameAr = "الأقصر", CityNameEn = "Luxor" },
                    new City {   GovernorateId = 24, CityNameAr = "الأقصر الجديدة", CityNameEn = "New Luxor" },
                    new City {   GovernorateId = 24, CityNameAr = "إسنا", CityNameEn = "Esna" },
                    new City {   GovernorateId = 24, CityNameAr = "طيبة الجديدة", CityNameEn = "New Tiba" },
                    new City {   GovernorateId = 24, CityNameAr = "الزينية", CityNameEn = "Al ziynia" },
                    new City {   GovernorateId = 24, CityNameAr = "البياضية", CityNameEn = "Al Bayadieh" },
                    new City {   GovernorateId = 24, CityNameAr = "القرنة", CityNameEn = "Al Qarna" },
                    new City {   GovernorateId = 24, CityNameAr = "أرمنت", CityNameEn = "Armant" },
                    new City {   GovernorateId = 24, CityNameAr = "الطود", CityNameEn = "Al Tud" },
                    new City {   GovernorateId = 25, CityNameAr = "قنا", CityNameEn = "Qena" },
                    new City {   GovernorateId = 25, CityNameAr = "قنا الجديدة", CityNameEn = "New Qena" },
                    new City {   GovernorateId = 25, CityNameAr = "ابو طشت", CityNameEn = "Abu Tesht" },
                    new City {   GovernorateId = 25, CityNameAr = "نجع حمادي", CityNameEn = "Nag Hammadi" },
                    new City {   GovernorateId = 25, CityNameAr = "دشنا", CityNameEn = "Deshna" },
                    new City {   GovernorateId = 25, CityNameAr = "الوقف", CityNameEn = "Alwaqf" },
                    new City {   GovernorateId = 25, CityNameAr = "قفط", CityNameEn = "Qaft" },
                    new City {   GovernorateId = 25, CityNameAr = "نقادة", CityNameEn = "Naqada" },
                    new City {   GovernorateId = 25, CityNameAr = "فرشوط", CityNameEn = "Farshout" },
                    new City {   GovernorateId = 25, CityNameAr = "قوص", CityNameEn = "Quos" },
                    new City {   GovernorateId = 26, CityNameAr = "العريش", CityNameEn = "Arish" },
                    new City {   GovernorateId = 26, CityNameAr = "الشيخ زويد", CityNameEn = "Sheikh Zowaid" },
                    new City {   GovernorateId = 26, CityNameAr = "نخل", CityNameEn = "Nakhl" },
                    new City {   GovernorateId = 26, CityNameAr = "رفح", CityNameEn = "Rafah" },
                    new City {   GovernorateId = 26, CityNameAr = "بئر العبد", CityNameEn = "Bir al-Abed" },
                    new City {   GovernorateId = 26, CityNameAr = "الحسنة", CityNameEn = "Al Hasana" },
                    new City {   GovernorateId = 27, CityNameAr = "سوهاج", CityNameEn = "Sohag" },
                    new City {   GovernorateId = 27, CityNameAr = "سوهاج الجديدة", CityNameEn = "Sohag El Gedida" },
                    new City {   GovernorateId = 27, CityNameAr = "أخميم", CityNameEn = "Akhmeem" },
                    new City {   GovernorateId = 27, CityNameAr = "أخميم الجديدة", CityNameEn = "Akhmim El Gedida" },
                    new City {   GovernorateId = 27, CityNameAr = "البلينا", CityNameEn = "Albalina" },
                    new City {   GovernorateId = 27, CityNameAr = "المراغة", CityNameEn = "El Maragha" },
                    new City {   GovernorateId = 27, CityNameAr = "المنشأة", CityNameEn = "almunsha'a" },
                    new City {   GovernorateId = 27, CityNameAr = "دار السلام", CityNameEn = "Dar AISalaam" },
                    new City {   GovernorateId = 27, CityNameAr = "جرجا", CityNameEn = "Gerga" },
                    new City {   GovernorateId = 27, CityNameAr = "جهينة الغربية", CityNameEn = "Jahina Al Gharbia" },
                    new City {   GovernorateId = 27, CityNameAr = "ساقلته", CityNameEn = "Saqilatuh" },
                    new City {   GovernorateId = 27, CityNameAr = "طما", CityNameEn = "Tama" },
                    new City {   GovernorateId = 27, CityNameAr = "طهطا", CityNameEn = "Tahta" },
                    new City {   GovernorateId = 27, CityNameAr = "الكوثر", CityNameEn = "Alkawthar" }
                };

                await context.Districts.AddRangeAsync(cities);
                await context.SaveChangesAsync();
            }
        }
    }
}